package primero;
// Generated 29 nov 2022 22:27:08 by Hibernate Tools 5.4.33.Final

/**
 * Partidos generated by hbm2java
 */
public class Partidos implements java.io.Serializable {

	private int codigo;
	private String equipoLocal;
	private String equipoVisitante;
	private Integer puntosLocal;
	private Integer puntosVisitante;
	private String temporada;

	public Partidos() {
	}

	public Partidos(int codigo) {
		this.codigo = codigo;
	}

	public Partidos(int codigo, String equipoLocal, String equipoVisitante, Integer puntosLocal,
			Integer puntosVisitante, String temporada) {
		this.codigo = codigo;
		this.equipoLocal = equipoLocal;
		this.equipoVisitante = equipoVisitante;
		this.puntosLocal = puntosLocal;
		this.puntosVisitante = puntosVisitante;
		this.temporada = temporada;
	}

	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	public String getEquipoLocal() {
		return this.equipoLocal;
	}

	public void setEquipoLocal(String equipoLocal) {
		this.equipoLocal = equipoLocal;
	}

	public String getEquipoVisitante() {
		return this.equipoVisitante;
	}

	public void setEquipoVisitante(String equipoVisitante) {
		this.equipoVisitante = equipoVisitante;
	}

	public Integer getPuntosLocal() {
		return this.puntosLocal;
	}

	public void setPuntosLocal(Integer puntosLocal) {
		this.puntosLocal = puntosLocal;
	}

	public Integer getPuntosVisitante() {
		return this.puntosVisitante;
	}

	public void setPuntosVisitante(Integer puntosVisitante) {
		this.puntosVisitante = puntosVisitante;
	}

	public String getTemporada() {
		return this.temporada;
	}

	public void setTemporada(String temporada) {
		this.temporada = temporada;
	}

}
